#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# ADR-077 PR-1 — Redis cache cutover + eviction + Pulse ingest. The code
# (config defaults, the pulse:work dev process, the app:prune-stale-cache
# schedule) ships in the PR; this wizard is the founder-only half that
# lives on the Forge box and in the repo's .env.example — nothing here is
# reachable from CI or an AI session.
#
# Run it ON YOUR OWN MACHINE (it edits ./backend/.env.example and opens
# Forge in a browser). The Forge site is "api.pekangame.space". Adjust the
# SITE_PATH / PHP_BIN below if your Forge setup differs.

# The repo is checked out at /home/forge/api.pekangame.space/ and the
# Laravel app is its backend/ subdir. Forge zero-downtime deploy is OFF,
# so there is NO current/ symlink. This path must match the existing
# `horizon` daemon's Directory field in Forge exactly.
SITE_PATH="/home/forge/api.pekangame.space/backend"
PHP_BIN="php8.4"
ENV_FILE="backend/.env.example"

TOTAL_STAGES=7

banner "ADR-077 PR-1 — Redis cache cutover (Forge + .env.example)"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Redis — memory cap + eviction policy"
say "volatile-lru evicts ONLY keys with a TTL, so a cache-key flood can"
say "never evict queued-job data (DB 0 has no TTLs). NOT delivered by the"
say "PR code — a live Redis config change."
warn "If Redis is left on the default 'noeviction', a full Redis REJECTS new"
warn "cache writes (they throw) instead of evicting — worse than today. Do"
warn "not skip the verify step."
step "ssh pekangame-prod   (user 'forge', box 157.245.203.250)"
say  "  — or Forge → server → Commands, one command per run."
step "Set it live and persist it to redis.conf (no restart, no downtime):"
note "    redis-cli CONFIG SET maxmemory 536870912"
note "    redis-cli CONFIG SET maxmemory-policy volatile-lru"
note "    redis-cli CONFIG REWRITE"
say  "  Each returns OK. If NOAUTH: prepend  -a \"\$(grep ^REDIS_PASSWORD /home/forge/api.pekangame.space/backend/.env | cut -d= -f2)\""
step "Verify — both must echo the new values:"
note "    redis-cli CONFIG GET maxmemory-policy   # => volatile-lru"
note "    redis-cli CONFIG GET maxmemory          # => 536870912"
confirm "Both verify commands returned the new values?" || {
  warn "Fix Redis before continuing — the rest of this cutover depends on it."
  exit 1
}

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Forge .env — cache store + Pulse keys"
say "The PR sets safe config defaults, but Forge's .env is the source of"
say "truth on the box — set these explicitly so a future reader sees them."
open_url "https://forge.laravel.com"
step "Forge → server → api.pekangame.space → Environment. Set / add:"
note "    CACHE_STORE=redis"
note "    REDIS_PULSE_DB=2"
note "    PULSE_INGEST_DRIVER=redis"
note "    PULSE_REDIS_CONNECTION=pulse"
note "    PULSE_SLOW_QUERIES_THRESHOLD=200"
note "    PULSE_SLOW_REQUESTS_THRESHOLD=500"
step "Leave SESSION_DRIVER=database untouched (sessions are a separate concern)."
step "Leave PRICE_SYNC_INTERVAL_MINUTES alone — the 10→60 change is PR-3, not this PR."
warn "PULSE_INGEST_DRIVER=redis + PULSE_REDIS_CONNECTION=pulse reference a"
warn "connection that only exists in THIS PR's code. If prod has not deployed"
warn "it yet, set ONLY CACHE_STORE=redis + REDIS_PULSE_DB now, and add the"
warn "four PULSE_* lines in stage 6 AFTER the deploy — otherwise pulse:work"
warn "throws 'Redis connection [pulse] not configured'."
step "Save. Do NOT deploy yet — stages 3 and 4 change the deploy first."
pause "Saved the Environment panel?"

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "Forge daemon — pulse:work"
say "With PULSE_INGEST_DRIVER=redis, recorder data lands in a Redis stream"
say "(DB 2) and 'pulse:work' drains it into the pulse_* MySQL tables. If"
say "nothing runs pulse:work, /pulse silently stops updating."
open_url "https://forge.laravel.com"
step "Forge → server → Daemons → New Daemon:"
note "    Command:     $PHP_BIN artisan pulse:work"
note "    Directory:   $SITE_PATH"
note "    User:        forge"
note "    Processes:   1"
step "Create it. Confirm it shows green/running (like the horizon + reverb daemons)."
confirm "pulse:work daemon is running?" || warn "Create it before deploying — Pulse data will stall otherwise."

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Forge deploy script — pulse:restart"
say "A deploy pulls new code; the long-running pulse:work process keeps the"
say "OLD code until restarted — exactly like Horizon needs horizon:terminate."
open_url "https://forge.laravel.com"
step "Forge → site → Deploy Script. Find the 'php artisan horizon:terminate' line."
step "Add this line right after it:"
note "    \$FORGE_PHP artisan pulse:restart"
step "Save the deploy script."
pause "Deploy script updated?"

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "Repo — .env.example"
say "$ENV_FILE could not be edited from the build session (.env* deny rule),"
say "so apply this one change and commit it onto the PR branch"
say "(feature/adr-077-cache-perf)."
step "Change the existing line:"
note "    CACHE_STORE=database   →   CACHE_STORE=redis"
step "Then, in the same block, add these lines:"
note "    REDIS_CACHE_DB=1"
note "    REDIS_PULSE_DB=2"
note ""
note "    PULSE_INGEST_DRIVER=redis"
note "    PULSE_REDIS_CONNECTION=pulse"
note "    PULSE_SLOW_QUERIES_THRESHOLD=200"
note "    PULSE_SLOW_REQUESTS_THRESHOLD=500"
if [[ -f "$ENV_FILE" ]] && grep -qE '^CACHE_STORE=redis' "$ENV_FILE" \
   && grep -qE '^PULSE_INGEST_DRIVER=redis' "$ENV_FILE"; then
  printf '  %s✓%s %s already has the new keys.\n' "$GREEN" "$RESET" "$ENV_FILE"
else
  confirm "Applied the change to $ENV_FILE?" || warn "Do it before merging the PR."
fi

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "Merge + deploy"
say "PR-1 has no migration, so ordering is simple: merge, then deploy."
step "Get feature/adr-077-cache-perf green in CI and merged into staging,"
step "then staging → main (--no-ff) per the branch workflow."
step "On the main merge: Forge auto-deploys. Watch the deploy log for:"
note "    - composer install + config:cache succeed"
note "    - 'php artisan pulse:restart' runs (the line from stage 4)"
note "    - horizon:terminate runs"
step "If auto-deploy is gated behind the CI 'deploy' job, use Forge 'Deploy Now'."
pause "Deploy finished green?"

# ── Stage 7 ──────────────────────────────────────────────────────────────
stage "Verify the cutover"
say "The first requests after deploy hit a cold Redis and rebuild every key"
say "— a handful of slow hits over ~60s on a low-traffic storefront, not an"
say "outage. Then check:"
open_url "https://api.pekangame.space/up"
step "https://api.pekangame.space/up  → 200"
step "SSH to the box and run:"
note "    redis-cli CONFIG GET maxmemory-policy      # volatile-lru (still)"
note "    redis-cli -n 1 DBSIZE                      # > 0 and growing (cache)"
note "    redis-cli -n 2 DBSIZE                      # small, drains toward 0 (pulse:work working)"
step "Open /pulse and confirm fresh entries appear within ~2 min (ingest is flowing)."
step "Load the storefront a few times — first hit or two slower, then fast."
step "Watch /pulse Slow Queries for a day: the 52s 'select from cache' must be gone."
confirm "All checks pass?" || warn "If /pulse went dark: check the pulse:work daemon. If writes throw: check stage 1's maxmemory-policy."

finish
