#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "ADR-084 PR-4 — docs.pekangame.space (Reseller API docs site)"

note "This wizard stands up docs-site/ as the 4th Vercel frontend and then"
note "flips the backend's /docs/api route to 301-redirect there. The code"
note "for all of it is already merged — this is the one-time infra + DNS."
note ""
note "Nothing is written to .env here; the only value captured is the one"
note "DNS record, which you add at your DNS provider."
pause "Ready?"

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Vercel — create the project"
say "Create a 4th Vercel project for docs-site/, alongside pekangame-admin,"
say "pekangame-storefront, and pekangame-reseller."
open_url "https://vercel.com/new"
step "Pick the team 'jw-brothers' (team id team_i9p6dY1gacYi2zjKEtI5dFe3)."
step "Import this Git repository (the same one the other 3 projects use)."
step "Project Name: pekangame-docs"
step "Framework Preset: Astro  (Vercel should auto-detect it)"
step "Root Directory: click 'Edit' and set it to  docs-site"
step "Build & Output Settings: leave the Astro defaults"
step "  (Build Command: astro build   ·   Output Directory: dist)"
step "Environment Variables: none needed."
step "Click Deploy and wait for the first build to go green."
note "The build runs 'npm run build' in docs-site/ — same as CI's docs-site job."
pause "First deployment is green?"

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "Vercel — add the domain"
say "Attach docs.pekangame.space to the new project."
open_url "https://vercel.com/jw-brothers/pekangame-docs/settings/domains"
step "In 'Add Domain', enter:  docs.pekangame.space  → Add"
step "Vercel will show a DNS record you must create. It is usually:"
step "    Type: CNAME   Name: docs   Value: cname.vercel-dns.com"
step "…but copy the EXACT value Vercel shows on your screen — it can differ."
ask DOCS_DNS_TARGET "Paste the CNAME target Vercel shows (e.g. cname.vercel-dns.com):"
note "Captured for the next stage. Nothing is written to disk."

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "DNS — add the CNAME"
say "Add the record at the DNS provider that hosts pekangame.space"
say "(the same one where connect.pekangame.space's CNAME already lives)."
open_url "https://dash.cloudflare.com/"
step "Open the pekangame.space zone → DNS → Records → Add record:"
step "    Type:   CNAME"
step "    Name:   docs"
step "    Target: ${DOCS_DNS_TARGET:-<the value from stage 2>}"
step "    Proxy status: DNS only (grey cloud) — Vercel terminates TLS itself"
step "    TTL: Auto"
step "Save, then go back to the Vercel Domains page and wait for"
step "'Valid Configuration' + the SSL certificate to be issued (a few minutes)."
pause "Vercel shows the domain as Valid with a certificate?"

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "Verify the docs site"
say "Confirm the site and the raw spec are both live on the real domain."
open_url "https://docs.pekangame.space"
step "The Starlight home page ('PekanGame Reseller API') should load."
open_url "https://docs.pekangame.space/openapi.json"
step "This should return raw JSON starting with {\"openapi\":\"3.1.0\", …"
step "Also click into 'API Reference' in the sidebar — the 5 operations"
step "(balance, catalog, list/place/get orders) should render."
if confirm "Both the site and /openapi.json look right?"; then
  say "Good — the docs site is live."
else
  warn "Stop here and fix the deploy before flipping the redirect."
  warn "Re-run this wizard once it's sorted (earlier stages are quick to re-confirm)."
  finish
  exit 1
fi

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "Forge — set DOCS_SITE_URL on the backend"
say "The backend keeps serving its built-in Scramble UI at /docs/api until"
say "this env var is set. Setting it flips /docs/api and /docs/api.json to a"
say "301 redirect to the docs site."
open_url "https://forge.laravel.com/servers"
step "Open server 'pekangame-prod' → site 'api.pekangame.space' → Environment."
step "Add this line to the .env, then Save:"
step "    DOCS_SITE_URL=https://docs.pekangame.space"
step "Then either click 'Deploy Now', or run over SSH:"
step "    ssh pekangame-prod"
step "    cd /home/forge/api.pekangame.space/backend && php artisan config:clear && php artisan config:cache"
pause "Env var saved and config re-cached (or redeployed)?"

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "Verify the redirect"
say "Final check — the old docs URL should now bounce to the new site."
open_url "https://api.pekangame.space/docs/api"
step "Your browser should land on https://docs.pekangame.space (a 301)."
step "Command-line check, if you have curl handy:"
step "    curl -sI https://api.pekangame.space/docs/api | grep -i '^location'"
step "    → location: https://docs.pekangame.space"
step "    curl -sI https://api.pekangame.space/docs/api.json | grep -i '^location'"
step "    → location: https://docs.pekangame.space/openapi.json"
if confirm "Both /docs/api and /docs/api.json 301 to the docs site?"; then
  say "Done. ADR-084 is fully live."
else
  warn "If it still shows the Scramble UI: the config cache is stale —"
  warn "re-run 'php artisan config:clear && php artisan config:cache' on the box."
fi

finish

note "Follow-ups (not part of this wizard):"
note "  - Add docs.pekangame.space to docs/prd.md's infra list."
note "  - On a future API change: regenerate docs-site/public/openapi.json"
note "    (cd backend && php artisan scramble:clear && php artisan scramble:export"
note "     --path=../docs-site/public/openapi.json --no-ansi --silent) — CI's"
note "    scramble-drift job fails the PR otherwise."
