#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# ── This procedure's own config + cleanup plumbing ───────────────────────────
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$REPO_ROOT/backend"
ENV_FILE="$BACKEND_DIR/.env"
LOCAL_BACKEND_URL="${LOCAL_BACKEND_URL:-https://kedairuncit-backend.test}"

TUNNEL_LOG="$(mktemp -t chip-tunnel.XXXXXX)"
WORKER_LOG="$(mktemp -t chip-worker.XXXXXX)"
TUNNEL_PID=""
WORKER_PID=""
ENV_TOUCHED=0

_cleanup() {
  set +e
  [[ -n "$WORKER_PID" ]] && kill "$WORKER_PID" 2>/dev/null
  [[ -n "$TUNNEL_PID" ]] && kill "$TUNNEL_PID" 2>/dev/null
  if [[ "$ENV_TOUCHED" == "1" && -f "$ENV_FILE" ]]; then
    local tmp; tmp=$(mktemp)
    grep -vE '^CHIP_CALLBACK_URL=' "$ENV_FILE" > "$tmp" && mv "$tmp" "$ENV_FILE"
    ( cd "$BACKEND_DIR" && php artisan config:clear >/dev/null 2>&1 )
    printf '\n  %s✓%s reverted CHIP_CALLBACK_URL in %s (back to the local default)\n' \
      "${GREEN:-}" "${RESET:-}" "$ENV_FILE"
  fi
  rm -f "$TUNNEL_LOG" "$WORKER_LOG"
}
trap _cleanup EXIT

banner "CHIP webhook tunnel test  (go-live step a)"

# ── Stage 1 ─────────────────────────────────────────────────────────────────
stage "Preflight — tools, Redis, CHIP test key"
say "Proves the CHIP success_callback path end to end against the real CHIP"
say "API, with a public tunnel to your local Herd backend. No real money —"
say "CHIP test key, mark_as_paid, Gamevion sandbox delivery."
printf '\n'

MISSING=0
for c in cloudflared php docker; do
  if command -v "$c" >/dev/null 2>&1; then
    note "found $c"
  else
    warn "missing: $c"; MISSING=1
  fi
done
[[ "$MISSING" == "1" ]] && { warn "install the missing tool(s) and re-run."; exit 1; }

if [[ ! -f "$ENV_FILE" ]]; then
  warn "no $ENV_FILE — run this from a checkout with a configured backend."; exit 1
fi

step "Starting the Redis container the queue driver needs..."
( cd "$BACKEND_DIR" && docker compose up -d redis ) || {
  warn "docker compose up -d redis failed — start Docker Desktop and re-run."; exit 1
}

step "Checking the CHIP key in $ENV_FILE..."
CHIP_KEY_SET=$( cd "$BACKEND_DIR" && php artisan tinker --execute="echo (config('services.chip.secret_key') && config('services.chip.brand_id')) ? 'yes' : 'no';" 2>/dev/null | tr -d '[:space:]' )
if [[ "$CHIP_KEY_SET" != "yes" ]]; then
  warn "CHIP_SECRET_KEY / CHIP_BRAND_ID not both set in $ENV_FILE."
  warn "This test needs a CHIP TEST-mode key. Add them and re-run."
  exit 1
fi
note "CHIP key + brand present (make sure it is the TEST-mode key, not live)"
pause "Preflight OK — press Enter."

# ── Stage 2 ─────────────────────────────────────────────────────────────────
stage "Open a public tunnel to the backend"
say "cloudflared gives you a throwaway https://<name>.trycloudflare.com URL"
say "that forwards to $LOCAL_BACKEND_URL — the address CHIP will POST the"
say "signed callback to."
printf '\n'

# --http-host-header: Herd routes vhosts by Host, so the origin request must
#   carry kedairuncit-backend.test, not the trycloudflare hostname.
# --no-tls-verify: don't choke on Herd's local origin cert.
LOCAL_BACKEND_HOST="${LOCAL_BACKEND_URL#*://}"
cloudflared tunnel --url "$LOCAL_BACKEND_URL" \
  --http-host-header "$LOCAL_BACKEND_HOST" \
  --no-tls-verify > "$TUNNEL_LOG" 2>&1 &
TUNNEL_PID=$!
step "tunnel starting (pid $TUNNEL_PID) — waiting for its URL..."

TUNNEL_URL=""
for _ in $(seq 1 40); do
  TUNNEL_URL=$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$TUNNEL_LOG" | head -n1 || true)
  [[ -n "$TUNNEL_URL" ]] && break
  if ! kill -0 "$TUNNEL_PID" 2>/dev/null; then
    warn "cloudflared exited early. Its log:"; sed 's/^/    /' "$TUNNEL_LOG"; exit 1
  fi
  sleep 1
done
[[ -z "$TUNNEL_URL" ]] && { warn "no tunnel URL after 40s. Log:"; sed 's/^/    /' "$TUNNEL_LOG"; exit 1; }

note "tunnel URL: $TUNNEL_URL"
CALLBACK_URL="$TUNNEL_URL/api/webhooks/chip"
ENV_TOUCHED=1
write_env CHIP_CALLBACK_URL "$CALLBACK_URL"
( cd "$BACKEND_DIR" && php artisan config:clear >/dev/null 2>&1 )
note "CHIP will be told to call: $CALLBACK_URL"
pause "Tunnel up — press Enter."

# ── Stage 3 ─────────────────────────────────────────────────────────────────
stage "Start a queue worker (for the delivery half)"
say "The webhook flips payment_status synchronously — that part works with or"
say "without a worker. delivery_status (Gamevion sandbox) runs on FulfillOrderJob,"
say "which needs a worker. Starting one for the duration of this test."
printf '\n'

( cd "$BACKEND_DIR" && php artisan queue:work redis --tries=1 --max-time=300 ) > "$WORKER_LOG" 2>&1 &
WORKER_PID=$!
sleep 2
if kill -0 "$WORKER_PID" 2>/dev/null; then
  note "queue worker running (pid $WORKER_PID)"
else
  warn "queue worker did not start — delivery_status may stay NotStarted. Log:"
  sed 's/^/    /' "$WORKER_LOG"
  confirm "Continue anyway (payment_status is still the real test)?" || exit 1
fi
pause "Press Enter to run the test."

# ── Stage 4 ─────────────────────────────────────────────────────────────────
stage "Run the end-to-end webhook test"
say "This creates ONE real CHIP test purchase + a local Order, calls"
say "mark_as_paid, and polls for the signed callback to land. The Order is"
say "deleted afterward (--cleanup)."
printf '\n'
confirm "Run app:chip-webhook-smoke-test now?" || { warn "skipped."; exit 0; }
printf '\n'

set +e
( cd "$BACKEND_DIR" && php artisan app:chip-webhook-smoke-test --cleanup --wait=90 )
TEST_RC=$?
set -e

printf '\n'
if [[ "$TEST_RC" == "0" ]]; then
  printf '  %s%s✓ webhook path verified end to end.%s\n' "${BOLD:-}" "${GREEN:-}" "${RESET:-}"
  note "signature (real GET /public_key/), parse, and Order → Paid all confirmed."
  note "If delivery_status showed Delivered, the whole pipeline is proven."
else
  printf '  %s%s✗ the test did not confirm the webhook.%s\n' "${BOLD:-}" "${RED:-}" "${RESET:-}"
  note "Check, in the command output above and the backend log:"
  note "  · 'Rejected CHIP webhook: invalid signature'  → key/verify issue"
  note "  · nothing logged at all                       → tunnel or CHIP_CALLBACK_URL wrong"
  note "  · 'no order found'                            → payment_ref mismatch"
  note "backend log: tail -f $BACKEND_DIR/storage/logs/laravel.log"
fi
pause "Press Enter to tear down."

# ── Stage 5 ─────────────────────────────────────────────────────────────────
stage "Tear down"
say "Stopping the tunnel + worker and reverting CHIP_CALLBACK_URL."
say "(The EXIT trap also does this if you Ctrl-C at any point.)"
_cleanup
trap - EXIT
TUNNEL_PID=""; WORKER_PID=""; ENV_TOUCHED=0
printf '\n'
if [[ "${TEST_RC:-1}" == "0" ]]; then
  note "Next go-live step (b): production + live CHIP key + one real RM1 FPX"
  note "payment through a temporarily-promoted cheap Gamevion package, then"
  note "flip the fpx payment_methods row is_active. See docs/adr.md ADR-022."
fi

finish
