#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=23

# This wizard captures no .env for the local repo — it builds the PRODUCTION
# env block for the Forge dashboard. Point ENV_FILE at a scratch file in $HOME
# so re-runs remember what you typed; shred it at the end (the wizard reminds).
ENV_FILE="${ENV_FILE:-$HOME/pekangame-forge.env}"

REPO="farresyh/topup-website"
DOMAIN="api.pekangame.space"
RESERVED_IP="137.184.250.200"
OLD_DROPLET_ID="596906796"
OLD_DROPLET_NAME="topup-prod-sgp1"
FORGE_SITE_PATH="/home/forge/${DOMAIN}"
FORGE_APP_PATH="${FORGE_SITE_PATH}/backend"
ADR066_MARKER="ADR-066"

# repo root — so git checks work no matter where this is run from
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"
[[ -d "$REPO_DIR/.git" ]] || REPO_DIR="$(git -C "$HOME/Desktop/KEROX/Project/kedairuncitsoloz" rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"

# ---- verification helpers -------------------------------------------------

# check "label" fn [args...] — run a verifier; on failure, offer to continue
# or bail (re-run resumes here since values are remembered).
check() {
  local label="$1"; shift
  printf '  %s… verifying:%s %s\n' "$DIM" "$RESET" "$label"
  if "$@" >/dev/null 2>&1; then
    printf '  %s✓ verified:%s %s\n' "$GREEN" "$RESET" "$label"
    return 0
  fi
  warn "could not verify: $label"
  if confirm "Continue anyway?"; then
    return 0
  fi
  printf '\n  %sStopped. Re-run this wizard when ready — it resumes at this stage.%s\n\n' "$DIM" "$RESET"
  exit 1
}

v_do_token() {
  curl -sf -o /dev/null -H "Authorization: Bearer ${DIGITALOCEAN_ACCESS_TOKEN}" \
    https://api.digitalocean.com/v2/account
}
v_dns_points_to_rip() {
  local got; got="$(dig +short "$DOMAIN" A 2>/dev/null | tail -n1)"
  [[ "$got" == "$RESERVED_IP" ]]
}
v_port_open()  { nc -z -w5 "$RESERVED_IP" "$1"; }
v_tls_cert()   {
  echo | openssl s_client -servername "$DOMAIN" -connect "${DOMAIN}:443" 2>/dev/null \
    | openssl x509 -noout -checkend 0 >/dev/null 2>&1
}
v_https_up()   { curl -sf -o /dev/null --max-time 10 "https://${DOMAIN}/up"; }
v_main_has_adr066() {
  git -C "$REPO_DIR" fetch -q origin 2>/dev/null || return 1
  git -C "$REPO_DIR" log origin/main --oneline -n 50 | grep -q "$ADR066_MARKER"
}
v_old_droplet_gone() {
  local code
  code="$(curl -s -o /dev/null -w '%{http_code}' \
    -H "Authorization: Bearer ${DIGITALOCEAN_ACCESS_TOKEN}" \
    "https://api.digitalocean.com/v2/droplets/${OLD_DROPLET_ID}")"
  [[ "$code" == "404" ]]
}
v_forge_hook() {
  [[ -n "${FORGE_DEPLOY_HOOK:-}" ]] && curl -sf -o /dev/null -X POST "$FORGE_DEPLOY_HOOK"
}
v_registry_gone() {
  local code
  code="$(curl -s -o /dev/null -w '%{http_code}' \
    -H "Authorization: Bearer ${DIGITALOCEAN_ACCESS_TOKEN}" \
    "https://api.digitalocean.com/v2/registry")"
  [[ "$code" == "404" ]]
}
v_admin_url()    { curl -sf -o /dev/null --max-time 10 "https://admin.pekangame.space"; }
v_store_url()    { curl -sf -o /dev/null --max-time 10 "https://pekangame.space"; }
v_reseller_url() { curl -sf -o /dev/null --max-time 10 "https://reseller.pekangame.space"; }

# ═════════════════════════════════════════════════════════════════════════

banner "PekanGame — Laravel Forge production cutover (ADR-066)"

note "Forge Growth plan: already upgraded. PR #49: already merged to staging."
note "Env values are written to: $ENV_FILE"
pause "Press Enter to begin."

# ── 1 ────────────────────────────────────────────────────────────────────
stage "DigitalOcean — API token for Forge"
say "Forge needs a DO API token to create and manage the droplet."
open_url "https://cloud.digitalocean.com/account/api/tokens"
step "Click 'Generate New Token'. Name it 'laravel-forge'."
step "Scopes: Full Access (or Custom with droplet + reserved_ip + firewall read/write)."
step "Expiry: No expiry (Forge manages the server long-term)."
step "Click Generate, then copy the token string (shown once)."
ask_secret DIGITALOCEAN_ACCESS_TOKEN "Paste the DO API token:"
write_env DIGITALOCEAN_ACCESS_TOKEN "$DIGITALOCEAN_ACCESS_TOKEN"
check "token is valid against the DO API" v_do_token

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Forge — create the server"
say "Provision a fresh droplet through Forge (it installs its own SSH key —"
say "this is what retires the old SSH-access blocker)."
open_url "https://forge.laravel.com/servers/new"
step "Provider: DigitalOcean → connect it with the token from stage 1 if not already linked."
step "Server Name: pekangame-prod"
step "Server Size: 4 GB RAM / 2 vCPUs  (the \$28/mo Regular Intel tier)"
step "Region: Singapore 1  (SGP1)"
step "PHP Version: PHP 8.4"
step "Database: MySQL 8  — you can leave the default; we use DO Managed MySQL, not this."
step "Post-Provision Recipe: none."
step "Click 'Create Server'. Provisioning takes ~8-12 minutes."
note "Forge shows the root/sudo password + its SSH key once — you don't need to save them,"
note "Forge keeps them. Wait until the server card shows a green 'active' dot."
pause "Server shows 'active'? Press Enter."
ask FORGE_SERVER_IP "Paste the new server's IP address (shown on the Forge server page):"
write_env FORGE_SERVER_IP "$FORGE_SERVER_IP"
check "the new server answers on SSH port 22" bash -c "nc -z -w5 '${FORGE_SERVER_IP}' 22"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "DigitalOcean — tag the new droplet 'topup-prod'"
say "The Cloud Firewall (topup-prod-fw) and the Managed MySQL trusted-source rule"
say "are both bound to the tag 'topup-prod'. The new droplet needs that tag or it"
say "can neither be reached on 80/443 nor connect to the database."
open_url "https://cloud.digitalocean.com/droplets"
step "Open the 'pekangame-prod' droplet."
step "Go to the 'Tags' section (right-hand panel or the 'Tags' tab)."
step "Add the tag:  topup-prod   (pick the existing one — do not make a new variant)."
pause "Tag added? Press Enter."
note "Verify in Networking → Firewalls → topup-prod-fw that 'pekangame-prod' now"
note "appears under 'Droplets' via the tag."
pause "Confirmed. Press Enter."

# ── 4 ────────────────────────────────────────────────────────────────────
stage "DigitalOcean — Managed MySQL connection details + CA cert"
say "Collect the DB password and download the CA certificate the app needs for TLS."
open_url "https://cloud.digitalocean.com/databases"
step "Open 'topup-prod-mysql' → 'Connection Details'."
step "User: pekangame_app   |   Database: pekangame"
step "Connection parameters dropdown → choose 'Connection string' or 'Flags'."
step "Copy the PASSWORD for pekangame_app."
step "Under 'Connection Details' click 'Download CA certificate' — saves ca-certificate.crt."
ask_secret DB_PASSWORD "Paste the pekangame_app password:"
write_env DB_PASSWORD "$DB_PASSWORD"
ask DO_CA_CERT_PATH "Full path to the downloaded ca-certificate.crt (e.g. ~/Downloads/ca-certificate.crt):"
# normalise ~ and store
DO_CA_CERT_PATH="${DO_CA_CERT_PATH/#\~/$HOME}"
write_env DO_CA_CERT_PATH "$DO_CA_CERT_PATH"
check "CA cert file exists and is a certificate" bash -c "grep -q 'BEGIN CERTIFICATE' '${DO_CA_CERT_PATH}'"
say "Also confirm the DB host — it should be the PRIVATE host (VPC), ending .ondigitalocean.com:"
ask DB_HOST "Paste the private DB host (no port), e.g. private-topup-prod-mysql-...ondigitalocean.com:"
write_env DB_HOST "$DB_HOST"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Forge — create the site (monorepo: web dir is /backend/public)"
say "The Laravel app lives in backend/ in this repo, not the repo root."
open_url "https://forge.laravel.com/servers"
step "Open 'pekangame-prod' → 'Sites' → 'New Site'."
step "Root Domain:  ${DOMAIN}"
step "Project Type: General PHP / Laravel"
step "Web Directory:  /backend/public      ← important, not /public"
step "PHP Version: PHP 8.4"
step "Leave 'Create Database' UNCHECKED (we use Managed MySQL)."
step "Click 'Add Site'."
pause "Site created? Press Enter."

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Forge — connect the Git repository"
open_url "https://forge.laravel.com/servers"
step "On the ${DOMAIN} site → 'Apps' tab → 'Git Repository'."
step "Provider: GitHub   |   Repository:  ${REPO}   |   Branch:  main"
step "UNCHECK 'Install Composer Dependencies' — our deploy script does it (from backend/)."
step "Click 'Install Repository'."
pause "Repository installed? Press Enter."
note "If Forge shows a GitHub auth prompt, authorise it for the ${REPO} repo."

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Forge — Environment file"
say "This wizard now builds the full production .env. You'll paste it into Forge."
say "It carries your existing supplier/payment secrets over from your LOCAL backend/.env."
echo
step "First: open your local backend/.env in another window — you'll copy 4 secret values."
pause "Ready? Press Enter to generate."

# generated values
APP_KEY_VALUE="base64:$(openssl rand -base64 32)"
REVERB_APP_ID_VALUE="$(openssl rand -hex 6)"
REVERB_APP_KEY_VALUE="$(openssl rand -hex 16)"
REVERB_APP_SECRET_VALUE="$(openssl rand -hex 32)"
write_env APP_KEY "$APP_KEY_VALUE"
write_env REVERB_APP_ID "$REVERB_APP_ID_VALUE"
write_env REVERB_APP_KEY "$REVERB_APP_KEY_VALUE"
write_env REVERB_APP_SECRET "$REVERB_APP_SECRET_VALUE"

say "Now the secrets from your local backend/.env (hidden input):"
ask_secret CHIP_SECRET_KEY   "CHIP_SECRET_KEY (from local backend/.env):"
ask_secret CHIP_BRAND_ID     "CHIP_BRAND_ID:"
ask_secret GAMEVION_API_KEY  "GAMEVION_API_KEY (or its equivalent key name — check local .env):"
ask_secret PLUNK_API_KEY     "PLUNK_API_KEY:"
write_env CHIP_SECRET_KEY  "$CHIP_SECRET_KEY"
write_env CHIP_BRAND_ID    "$CHIP_BRAND_ID"
write_env GAMEVION_API_KEY "$GAMEVION_API_KEY"
write_env PLUNK_API_KEY    "$PLUNK_API_KEY"

say "First super-admin account (ProductionSeeder reads these on the first seed):"
ask        ADMIN_EMAIL    "ADMIN_EMAIL:"
ask_secret ADMIN_PASSWORD "ADMIN_PASSWORD (min 12 chars):"
write_env ADMIN_EMAIL    "$ADMIN_EMAIL"
write_env ADMIN_PASSWORD "$ADMIN_PASSWORD"

FORGE_ENV_OUT="$HOME/pekangame-forge-DOTENV.txt"
cat > "$FORGE_ENV_OUT" <<EOF
APP_NAME=PekanGame
APP_ENV=production
APP_KEY=${APP_KEY_VALUE}
APP_DEBUG=false
APP_URL=https://${DOMAIN}

LOG_CHANNEL=stack
LOG_LEVEL=warning

DB_CONNECTION=mysql
DB_HOST=${DB_HOST}
DB_PORT=25060
DB_DATABASE=pekangame
DB_USERNAME=pekangame_app
DB_PASSWORD=${DB_PASSWORD}
MYSQL_ATTR_SSL_CA=${FORGE_APP_PATH}/storage/certs/do-mysql-ca.crt

SESSION_DRIVER=database
SESSION_LIFETIME=120

CACHE_STORE=database

REDIS_CLIENT=predis
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=null

QUEUE_CONNECTION=redis
HORIZON_PREFIX=pekangame_horizon

BROADCAST_CONNECTION=reverb
REVERB_APP_ID=${REVERB_APP_ID_VALUE}
REVERB_APP_KEY=${REVERB_APP_KEY_VALUE}
REVERB_APP_SECRET=${REVERB_APP_SECRET_VALUE}
REVERB_HOST=127.0.0.1
REVERB_PORT=8080
REVERB_SCHEME=http
REVERB_SERVER_HOST=0.0.0.0
REVERB_SERVER_PORT=8080

MAIL_MAILER=log

ADMIN_URL=https://admin.pekangame.space
STOREFRONT_URL=https://pekangame.space
RESELLER_PORTAL_URL=https://reseller.pekangame.space

ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

GAMEVION_SANDBOX=true
GAMEVION_API_KEY=${GAMEVION_API_KEY}

CHIP_SECRET_KEY=${CHIP_SECRET_KEY}
CHIP_BRAND_ID=${CHIP_BRAND_ID}

PLUNK_API_KEY=${PLUNK_API_KEY}
EOF
printf '  %s✓ wrote%s full production .env → %s\n' "$GREEN" "$RESET" "$FORGE_ENV_OUT"
warn "review $FORGE_ENV_OUT — add any other keys your local backend/.env has that"
warn "production needs (extra Gamevion/CHIP/Plunk vars, GA/pixel IDs, etc.)."
open_url "https://forge.laravel.com/servers"
step "On the ${DOMAIN} site → 'Environment' → paste the ENTIRE contents of:"
step "   ${FORGE_ENV_OUT}"
step "Click 'Save'."
pause "Environment saved in Forge? Press Enter."

# ── 8 ────────────────────────────────────────────────────────────────────
stage "Forge — deploy script"
say "Replace the default deploy script with the ADR-066 one (runs from backend/)."
DEPLOY_OUT="$HOME/pekangame-forge-DEPLOY.sh"
cat > "$DEPLOY_OUT" <<EOF
cd ${FORGE_SITE_PATH}
git pull origin main
cd ${FORGE_APP_PATH}
\$FORGE_COMPOSER install --no-dev --no-interaction --prefer-dist --optimize-autoloader
\$FORGE_PHP artisan migrate --force
\$FORGE_PHP artisan config:cache
\$FORGE_PHP artisan route:cache
\$FORGE_PHP artisan event:cache
\$FORGE_PHP artisan storage:link
\$FORGE_PHP artisan horizon:terminate || true
( flock -w 10 9 || exit 1
    echo 'Reloading FPM...'; sudo -S service \$FORGE_PHP_FPM reload ) 9>/tmp/fpmlock
sleep 3
curl -fsS --max-time 10 https://${DOMAIN}/up
EOF
printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$DEPLOY_OUT"
open_url "https://forge.laravel.com/servers"
step "${DOMAIN} site → 'Apps' → 'Deploy Script' → paste the contents of ${DEPLOY_OUT}."
step "Make sure 'Quick Deploy' is OFF (we deploy from CI after tests, not on raw push)."
step "Click 'Save'."
pause "Deploy script saved, Quick Deploy OFF? Press Enter."

# ── 9 ────────────────────────────────────────────────────────────────────
stage "Forge — Redis persistence (AOF)"
say "The queue holds real un-processed jobs now (paid orders awaiting fulfilment),"
say "so Redis must survive a restart. Turn on append-only persistence."
open_url "https://forge.laravel.com/servers"
step "pekangame-prod server → 'Redis' (left nav, under the server)."
step "If Forge exposes an 'Append Only File' / persistence toggle, enable it."
step "Otherwise: server → 'Files' → edit /etc/redis/redis.conf → set:  appendonly yes"
step "         then server → 'Meta' / SSH terminal:  sudo service redis-server restart"
pause "AOF enabled + Redis restarted? Press Enter."
note "Also set a memory cap in redis.conf:  maxmemory 512mb  /  maxmemory-policy noeviction"

# ── 10 ───────────────────────────────────────────────────────────────────
stage "Forge — Reverb daemon"
say "Reverb (realtime WebSocket server, ADR-047) runs as a long-lived daemon."
open_url "https://forge.laravel.com/servers"
step "pekangame-prod server → 'Daemons' → 'New Daemon'."
step "Command:   php8.4 artisan reverb:start --host=0.0.0.0 --port=8080"
step "Directory: ${FORGE_APP_PATH}"
step "User: forge   |   Processes: 1"
step "Click 'Create'. It should show 'running' within a few seconds."
pause "Reverb daemon running? Press Enter."

# ── 11 ───────────────────────────────────────────────────────────────────
stage "Forge — Nginx: /app/ proxy for Reverb"
say "Browsers reach Reverb through one TLS surface: nginx proxies /app/ to :8080."
NGINX_OUT="$HOME/pekangame-forge-NGINX-app-block.txt"
cat > "$NGINX_OUT" <<'EOF'
    # Reverb WebSocket (ADR-047 / ADR-066) — proxy /app/ to the Reverb daemon
    location /app/ {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 60s;
    }
EOF
printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$NGINX_OUT"
open_url "https://forge.laravel.com/servers"
step "${DOMAIN} site → 'Apps' or the site menu → 'Nginx Configuration' ('Edit Files')."
step "Paste the block from ${NGINX_OUT} INSIDE the 'server { ... }' block,"
step "just above the existing 'location / { ... }' line."
step "Click 'Save' — Forge tests the config and reloads nginx."
pause "Nginx block added and saved (no error)? Press Enter."

# ── 12 ───────────────────────────────────────────────────────────────────
stage "Forge — Horizon"
say "Horizon supervises the queue workers, reading config/horizon.php's four"
say "per-queue supervisors (orders / price-sync / backups / supplier-request-logs)."
open_url "https://forge.laravel.com/servers"
step "${DOMAIN} site → 'Queue' tab → enable 'Horizon' (Forge manages 'php artisan horizon')."
step "Confirm the environment shows APP_ENV=production (from stage 7) so it picks the"
step "'production' supervisor block."
pause "Horizon enabled? Press Enter."
note "It will only actually start once the first deploy has pulled the code + vendor/."

# ── 13 ───────────────────────────────────────────────────────────────────
stage "DigitalOcean — move the Reserved IP to the new droplet"
say "DNS for ${DOMAIN} already points at ${RESERVED_IP}. Moving the Reserved IP"
say "onto pekangame-prod makes the domain resolve there. No live traffic exists yet,"
say "so there's nothing to interrupt."
open_url "https://cloud.digitalocean.com/networking/reserved_ips"
step "Find ${RESERVED_IP} (currently on ${OLD_DROPLET_NAME})."
step "Click the '...' menu → 'Reassign Reserved IP' → select 'pekangame-prod' → Reassign."
pause "Reassigned? Press Enter (DNS/routing can take 1-2 min)."
check "${DOMAIN} resolves to ${RESERVED_IP}" v_dns_points_to_rip
check "port 80 is reachable on ${RESERVED_IP} (new droplet + firewall tag)" v_port_open 80

# ── 14 ───────────────────────────────────────────────────────────────────
stage "Forge — SSL (Let's Encrypt)"
say "Now that the domain resolves to this server, issue the certificate."
open_url "https://forge.laravel.com/servers"
step "${DOMAIN} site → 'SSL' → 'Let's Encrypt' → domain ${DOMAIN} → 'Obtain Certificate'."
step "When it finishes, click 'Activate' if Forge doesn't auto-activate it."
pause "Certificate obtained + activated? Press Enter."
check "a valid, unexpired TLS certificate is served for ${DOMAIN}" v_tls_cert

# ── 15 ───────────────────────────────────────────────────────────────────
stage "GitHub — merge staging → main"
say "main is the deploy branch. It needs ADR-066 (Docker removed, Forge CI) before"
say "the first Forge deploy pulls it."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "Opening a staging → main PR..."
  gh pr create --repo "$REPO" --base main --head staging \
    --title "release: staging → main (ADR-066 Forge cutover)" \
    --body "Promotes ADR-066 (Forge deploy, Docker artifacts removed) plus everything already verified on staging. Merge with a merge commit (--no-ff), per AGENTS.md." \
    2>/dev/null || note "(PR may already exist — that's fine.)"
  gh pr view --repo "$REPO" staging --web 2>/dev/null || open_url "https://github.com/${REPO}/compare/main...staging"
else
  open_url "https://github.com/${REPO}/compare/main...staging"
  step "Click 'Create pull request', base = main, compare = staging."
fi
step "Wait for CI to go green on the PR."
step "Merge it — use 'Create a merge commit' (NOT squash), per the repo's workflow."
pause "Merged to main? Press Enter."
check "origin/main now contains the ${ADR066_MARKER} commit" v_main_has_adr066

# ── 16 ───────────────────────────────────────────────────────────────────
stage "Forge — first deploy"
open_url "https://forge.laravel.com/servers"
step "${DOMAIN} site → 'Apps' → 'Deploy Now'."
step "Watch the deploy log. The first run is the slow one (full composer install)."
step "It ends by curl-ing https://${DOMAIN}/up — the deploy fails if that isn't 200."
pause "Deploy finished green? Press Enter."
check "GET https://${DOMAIN}/up returns 200" v_https_up

# ── 17 ───────────────────────────────────────────────────────────────────
stage "First-boot — seed the production database"
say "The schema is migrated (deploy script). Now seed the one-time production data"
say "and create the first super admin from ADMIN_EMAIL / ADMIN_PASSWORD."
open_url "https://forge.laravel.com/servers"
step "${DOMAIN} site → open the web SSH terminal (or 'Commands' → run a command)."
step "Run, one line:"
say  "   cd ${FORGE_APP_PATH} && php artisan db:seed --class=ProductionSeeder --force"
step "Expect: primary reseller + branding + payment methods + crawler rules + hero slide,"
step "and 'Created super admin: <your email>'."
pause "Seed completed without error? Press Enter."
say "Now confirm you can log in:"
open_url "https://${DOMAIN}/up"
step "(Admin UI itself is on Vercel — stages 22-23. For now just confirm the API is healthy.)"
pause "Press Enter."

# ── 18 ───────────────────────────────────────────────────────────────────
stage "DigitalOcean — destroy the old droplet"
warn "IRREVERSIBLE. Only proceed once ${DOMAIN}/up is green on the NEW server (stage 16)."
say "Old droplet: ${OLD_DROPLET_NAME}  (id ${OLD_DROPLET_ID}) — the empty box that"
say "was created without an SSH key. Nothing runs on it."
check "the new server is serving /up over HTTPS right now" v_https_up
open_url "https://cloud.digitalocean.com/droplets"
step "Open '${OLD_DROPLET_NAME}' → 'Destroy' → 'Destroy this Droplet'."
step "Type the droplet name to confirm when DO asks."
if confirm "Have you destroyed ${OLD_DROPLET_NAME} in the DO panel?"; then
  check "DO API no longer knows droplet ${OLD_DROPLET_ID}" v_old_droplet_gone
else
  SKIPPED+=("Destroy old droplet ${OLD_DROPLET_NAME} (id ${OLD_DROPLET_ID})")
  warn "left for later — do it once you're confident in the new server."
fi

# ── 19 ───────────────────────────────────────────────────────────────────
stage "GitHub — FORGE_DEPLOY_HOOK secret + verify auto-deploy"
say "CI's 'deploy' job POSTs this URL after the 5 test jobs pass on main."
open_url "https://forge.laravel.com/servers"
step "${DOMAIN} site → 'Apps' → 'Deploy Trigger' (or 'Deployment') → copy the URL."
step "It looks like: https://forge.laravel.com/servers/NNNN/sites/MMMM/deploy/http?token=..."
ask_secret FORGE_DEPLOY_HOOK "Paste the Forge deploy webhook URL:"
write_env FORGE_DEPLOY_HOOK "$FORGE_DEPLOY_HOOK"
set_secret FORGE_DEPLOY_HOOK "$FORGE_DEPLOY_HOOK"
say "Test it fires a deploy:"
check "POST to the hook is accepted by Forge" v_forge_hook
step "Check the Forge deploy log shows a deployment that was just queued/started."
pause "Deploy triggered by the hook? Press Enter."

# ── 20 ───────────────────────────────────────────────────────────────────
stage "Cleanup — retire the Docker-path resources"
say "None of these are used any more (ADR-066)."
open_url "https://cloud.digitalocean.com/registry"
step "DO Container Registry → Settings → 'Delete Registry' (the 'pekangame' registry, \$5/mo)."
pause "Registry deleted? Press Enter."
check "DO API reports no container registry" v_registry_gone
say "Stale GitHub secrets (no longer referenced by ci.yml):"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  for s in DIGITALOCEAN_ACCESS_TOKEN DEPLOY_HOST DEPLOY_USER DEPLOY_SSH_KEY; do
    if gh secret delete "$s" --repo "$REPO" >/dev/null 2>&1; then
      printf '  %s✓ deleted%s GitHub secret %s\n' "$GREEN" "$RESET" "$s"
    else
      note "  (secret $s not present — nothing to delete)"
    fi
  done
else
  open_url "https://github.com/${REPO}/settings/secrets/actions"
  step "Delete: DIGITALOCEAN_ACCESS_TOKEN, DEPLOY_HOST, DEPLOY_USER, DEPLOY_SSH_KEY"
  pause "Deleted? Press Enter."
fi

# ── 21 ───────────────────────────────────────────────────────────────────
stage "Monitoring — DO alerts + external uptime check"
say "ADR-020's addendum made these mandatory, not optional."
open_url "https://cloud.digitalocean.com/monitoring/alerts"
step "Create Alert Policy → CPU > 60% for 5 min → notify your email → apply to 'pekangame-prod'."
step "Create Alert Policy → Memory > 70% for 5 min → same."
step "Create Alert Policy → Disk > 80% → same."
pause "Three alert policies created? Press Enter."
open_url "https://dashboard.uptimerobot.com/monitors"
step "New monitor → HTTP(s) → URL: https://${DOMAIN}/up → interval 5 min → alert contact = you."
pause "Uptime monitor live? Press Enter."
note "Optional: also add https://forge.laravel.com health-check heartbeats on the Horizon"
note "and Reverb daemons (Forge → server → 'Monitoring')."

# ── 22 ───────────────────────────────────────────────────────────────────
stage "Vercel — import the three frontends"
say "storefront / admin / reseller each become a Vercel project on the JW Brothers team."
open_url "https://vercel.com/new"
say "For EACH of the three (repeat this stage's steps 3x):"
step "Import ${REPO} → team: JW Brothers."
step "storefront:  Root Directory = storefront   | Framework = Next.js"
step "admin:       Root Directory = admin"
step "reseller:    Root Directory = reseller"
step "Environment Variables (all three):"
say  "   NEXT_PUBLIC_API_URL=https://${DOMAIN}"
say  "   NEXT_PUBLIC_REVERB_APP_KEY=${REVERB_APP_KEY_VALUE}"
say  "   NEXT_PUBLIC_REVERB_HOST=${DOMAIN}"
say  "   NEXT_PUBLIC_REVERB_PORT=443"
say  "   NEXT_PUBLIC_REVERB_SCHEME=https"
step "admin + reseller ALSO need:  NEXT_PUBLIC_SITE_URL  and the PrimeReact licence key"
step "   (NEXT_PUBLIC_PRIMEUI_LICENSE_KEY — from your local admin/.env.local)."
step "storefront also:  NEXT_PUBLIC_SITE_URL=https://pekangame.space"
step "Deploy each. Note the *.vercel.app URL it gives you."
pause "All three projects deployed on *.vercel.app? Press Enter."

# ── 23 ───────────────────────────────────────────────────────────────────
stage "Vercel — custom domains + DNS"
say "Point the three hostnames at their Vercel projects. DNS is at Vercel already,"
say "so adding the domain in the project auto-creates the record."
open_url "https://vercel.com"
step "storefront project → Settings → Domains → add:  pekangame.space  (+ www redirect)."
step "admin project     → Settings → Domains → add:  admin.pekangame.space"
step "reseller project  → Settings → Domains → add:  reseller.pekangame.space"
step "Each shows 'Valid Configuration' once the record propagates (usually < 1 min at Vercel DNS)."
pause "All three domains valid? Press Enter."
check "https://pekangame.space responds"          v_store_url
check "https://admin.pekangame.space responds"    v_admin_url
check "https://reseller.pekangame.space responds" v_reseller_url

# ═════════════════════════════════════════════════════════════════════════

finish

printf '  %sNext, outside this wizard:%s\n' "$BOLD" "$RESET"
note "  - CHIP go-live: FPX approval → webhook config on the live domain → real test payment"
note "    → activate the 'fpx' payment_methods row."
note "  - Digiflazz: whitelist the egress IP (run 'curl -s ifconfig.me' in the Forge"
note "    web terminal) + ${RESERVED_IP} at Digiflazz; build the webhook controller."
note "  - Update docs/prd.md §14/§15 + the production memory: cutover DONE, go-live pending."
printf '\n'
warn "SHRED the local secret files now:"
note "  shred -u \"$ENV_FILE\" \"$HOME/pekangame-forge-DOTENV.txt\" 2>/dev/null || rm -f \"$ENV_FILE\" \"$HOME/pekangame-forge-DOTENV.txt\""
printf '\n'
